.PHONY: clean-pycache clean-ruff-cache clean-mypy-cache clean-all \
        lint format imports mypy pretty all dev prod \
		create_collection docker_dev docker_dev_detach docker_dev_logs docker_dev_stop \
		docker_build docker_run docker_logs docker_stop docker_clear_cache \
		docker_build_runpod docker_push_runpod


include .env

# ------------------------------------------------------------------------------
# Cleaning Targets
# ------------------------------------------------------------------------------
# These targets remove various cache directories generated by Python tools.
clean-pycache:
	find ./ -type d -name '__pycache__' -exec rm -rf {} +

clean-ruff-cache:
	find ./ -type d -name '.ruff_cache' -exec rm -rf {} +

clean-mypy-cache:
	find ./ -type d -name '.mypy_cache' -exec rm -rf {} +

# Removes all caches (pycache, ruff_cache, and mypy_cache).
clean-all: clean-pycache clean-ruff-cache clean-mypy-cache

# ------------------------------------------------------------------------------
# Code Quality and Formatting Targets
# ------------------------------------------------------------------------------
# Lint the code and automatically fix issues where possible.
lint:
	uv run ruff check src/* --fix
	uv run ruff check server.py --fix

# Format the code using Ruff's built-in formatting capabilities.
format:
	uv run ruff format src/*
	uv run ruff format server.py

# Sort imports using Ruff, automatically fixing them.
imports:
	uv run ruff check src/* --select I --fix
	uv run ruff check server.py --select I --fix

# Perform static type checking with mypy.
mypy:
	uv run mypy src server.py

# Run all code quality improvements: linting, formatting, and sorting imports.
pretty: lint format imports

# ------------------------------------------------------------------------------
# Meta Targets
# ------------------------------------------------------------------------------
# Run all code quality checks (lint, format, imports), static type checks,
# and then clean up caches.
all: pretty mypy clean-all

# ------------------------------------------------------------------------------
# Run Targets
# ------------------------------------------------------------------------------
create_collection:
	uv run python scripts/create_collection.py


# Run the server in development mode with hot-reloading.
dev:
	uv run uvicorn server:app \
		--host 0.0.0.0 \
		--port 8000 \
		--reload

# Run the server in production mode without reloading.
# Note: For GPU workloads, stick to 1 worker per GPU since each worker loads its own model copy (~8GB).
prod:
	uv run uvicorn server:app \
		--host 0.0.0.0 \
		--port 8000 \
		--workers 1

# ------------------------------------------------------------------------------
# Docker (Development - with auto-reload)
# ------------------------------------------------------------------------------

docker_dev:
	docker compose up --build

docker_dev_detach:
	docker compose up -d

docker_dev_logs:
	docker compose logs -f --tail=100

docker_dev_stop:
	docker compose down

# ------------------------------------------------------------------------------
# Docker (Production - no auto-reload)
# ------------------------------------------------------------------------------

docker_build:
	docker build -t colpali:latest .

docker_run:
	docker run --rm --name colpali_rag --env-file .env -v colpali_hf_cache:/root/.cache/huggingface -p 8000:8000 -d colpali:latest

docker_logs:
	docker logs -f --tail=100 colpali_rag

docker_stop:
	docker stop colpali_rag

docker_clear_cache:
	docker volume rm colpali_hf_cache || true

# ------------------------------------------------------------------------------
# Docker (RunPod - GPU optimized with pre-downloaded model)
# ------------------------------------------------------------------------------

docker_build_runpod:
	docker build -f Dockerfile.runpod -t colpali-rag-app:runpod .

docker_push_runpod:
	docker tag colpali-rag-app:runpod $(DOCKERHUB_USERNAME)/colpali-rag-app:latest
	docker push $(DOCKERHUB_USERNAME)/colpali-rag-app:latest